src/accountant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from accountant import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('the_counter.urls', namespace='the_counter')),

    # Reset and Change password
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

src/the_counter/urls.py
from django.urls import path, re_path
from . import views
"""Defines URL schemes for the_counter"""

app_name = 'the_counter'
urlpatterns = [
    # Home page
    path('', views.index, name="index"),

    # Budget parts
    path('budget/', views.budget, name="budget_parts"),

    # Income_Records
    path('budget/income/', views.income_records, name="income_records"),

    # Expenses_Records
    path('budget/expenses/', views.expenses_records, name="expenses_records"),

    # WishList_Records
    path('budget/wish_list/', views.wish_list, name="wish_list"),

    # New_Record
    path('budget/new_record/', views.new_record, name="new_record"),

    # Edit_Record
    re_path(r'^edit_record/(?P<record_id>\d+)/$', views.edit_record, name="edit"),

    # Delete_Record
    re_path(r'^delete_record/(?P<record_id>\d+)/$', views.delete_record, name="delete"),
]

src/users/urls.py
from django.urls import path

from . import views

"""Defines URL schemes for users"""

app_name = 'users'
urlpatterns = [
    # Registration
    path('register/', views.registration_view, name='register'),

    # Login page
    path('login/', views.login_view, name='login'),

    # Logout
    path('logout/', views.logout_view, name='logout'),

    # User Account
    path('user/', views.account_view, name='user'),

]

src/the_counter/models.py
from django.db import models
from datetime import date


class Record(models.Model):
    """"New budget record"""
    class Item(models.TextChoices):
        INCOME = 'income', 'Текущие доходы'
        EXPENSES = 'expenses', 'Текущие расходы'
        WISHLIST = 'wish_list', 'Лист желаний'

    budget_item = models.CharField(
        max_length=9,
        choices=Item.choices,
        default=Item.INCOME,
        verbose_name='Статья бюджета'
    )

    money = models.FloatField(verbose_name='Размер')
    item_description = models.CharField(max_length=200, verbose_name='Описание')
    date_added = models.DateField(default=date.today, verbose_name='Дата')

    def __str__(self):
        """Returns the stream representation of the model"""
        return ' - '.join([str(self.money), self.item_description])

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

src/the_counter/forms.py
from django.forms import ModelForm, Textarea
from .models import Record
from django.utils.translation import gettext_lazy as _


class RecordForm(ModelForm):
    class Meta:
        model = Record
        fields = '__all__'
        # exclude = ['date_added']
        labels = {
            'item_description': _('Назначение'),
        }
        help_texts = {
            'item_description': _('Добавьте описание вашей записи'),
        }
        error_messages = {
            'item_description': {
                'max_length': _("Максимальная длинна поля должна не привышать 200 символов"),
            },
        }
        widgets = {
            'item_description': Textarea(attrs={'cols': 80, 'rows': 2}),
        }

src/the_counter/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Record
from .forms import RecordForm


def index(request):
    """Home page of The_counter apps"""
    return render(request, 'the_counter/index.html')


def budget(request):
    """Shows budget parts"""
    income = 0
    expenses = 0
    wishes = 0
    eggs = Record.objects.all()
    for spam in eggs:
        if spam.budget_item == 'income':
            income += spam.money
        elif spam.budget_item == 'expenses':
            expenses += spam.money
        elif spam.budget_item == 'wish_list':
            wishes += spam.money
    context = {'income': income, 'expenses': expenses, 'wishes': wishes}
    return render(request, 'the_counter/budget_parts.html', context)


def income_records(request):
    """List of Income records"""
    records = Record.objects.filter(budget_item='income')
    context = {'records': records}
    return render(request, 'the_counter/income_records.html', context)


def expenses_records(request):
    """List of Expenses records"""
    records = Record.objects.filter(budget_item='expenses')
    context = {'records': records}
    return render(request, 'the_counter/expenses_records.html', context)


def wish_list(request):
    """List of Wish_list records"""
    records = Record.objects.filter(budget_item='wish_list')
    context = {'records': records}
    return render(request, 'the_counter/wish_list.html', context)


def new_record(request):
    """Adding a new record"""
    if request.method != 'POST':
        # Data have not been send, creating empty form
        form = RecordForm()
    else:
        # POST data sent, process data
        form = RecordForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('budget_parts'))

    context = {'form': form}
    return render(request, 'the_counter/new_record.html', context)


def edit_record(request, record_id):
    """Edits an existing record"""
    record = Record.objects.get(id=record_id)

    if request.method != 'POST':
        # Original request; the form is filled with the data of the current record
        form = RecordForm(instance=record)
    else:
        # Sending POST data; process data
        form = RecordForm(instance=record, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('budget_parts'))

    context = {'record': record, 'form': form}
    return render(request, 'the_counter/edit_record.html', context)


def delete_record(request, record_id):
    """Delete record"""
    record = Record.objects.get(id=record_id)
    record.delete()
    return HttpResponseRedirect(reverse('budget_parts'))

src/the_counter/templates/the_counter/base.html
<!DOCTYPE html>
<html>

  <head>
    <title>The Counter</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include 'snippets/header.html' %}
  </head>

  <body>

    <!-- Body -->
    <div class="main">
      {% block content %}

      {% endblock content %}
    </div>
    <!-- End Body -->

    {% include 'snippets/footer.html' %}

  </body>

</html>

src/the_counter/templates/the_counter/budget_parts.html
{% extends "the_counter/base.html" %}

{% block content %}

    <p>Статьи бюджета</p>
    <ul>
        <li><p><a href="{% url 'the_counter:income_records' %}">Текущие доходы</a> {{ income }}</p></li>
        <li><p><a href="{% url 'the_counter:expenses_records' %}">Текущие расходы</a> {{ expenses }}</p></li>
        <li><p><a href="{% url 'the_counter:wish_list' %}">Лист желаний</a> {{ wishes }}</p></li>
    </ul>

    <button onclick="document.location='new_record/'">Добавить новую запись</button>

{% endblock content %}

src/the_counter/templates/the_counter/edit_record.html
{% extends "the_counter/base.html" %}

{% block content %}

<p>Редактирование записи:</p>
<form action="{% url 'the_counter:edit_record' record.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Сохранить изменения</button>
</form>

{% endblock content %}

src/the_counter/templates/the_counter/expenses_records.html
{% extends "the_counter/base.html" %}

{% block content %}

    <p>Раздел: Текущие расходы</p>
    <p>Записи: </p>
    <ul>
        {% for record in records %}
            <li>{{ record.date_added|date:"M d" }} : {{ record }}</li>
                <a href="{% url 'the_counter:edit' record.id %}">Редактировать</a>
                <a href="{% url 'the_counter:delete' record.id %}">Удалить</a>
        {% empty %}
            <li>Ни одной записи ещё не было добавлено.</li>
        {% endfor %}
    </ul>

{% endblock content %}

src/the_counter/templates/the_counter/income_records.html
{% extends "the_counter/base.html" %}

{% block content %}

    <p>Раздел: Текущие доходы</p>
    <p>Записи: </p>
    <ul>
        {% for record in records %}
            <li>{{ record.date_added|date:"M d" }} : {{ record }} </li>
            <p>
                <a href="{% url 'the_counter:edit' record.id %}">Редактировать</a>
                <a href="{% url 'the_counter:delete' record.id %}">Удалить</a>
            </p>
        {% empty %}
            <li>Ни одной записи ещё не было добавлено.</li>
        {% endfor %}
    </ul>

{% endblock content %}

src/the_counter/templates/the_counter/index.html
{% extends "the_counter/base.html" %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">The Counter</h1>
  <p class="lead">Теперь следить за своими средствами стало проще! Отслеживайте ваш бюджет,
      добавляя записи о доходах и расходах. Используйте Лист Желаний The Counter и Вы сможете запланировать
      большую покупку без ущерба для вашего бюджета.
  </p>
</div>
<p></p>

{% endblock content %}

src/the_counter/templates/the_counter/new_record.html
{% extends "the_counter/base.html" %}

{% block content %}

<p>Добавить новую запись:</p>
<form action="{% url 'the_counter:new_record' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Добавить запись</button>
</form>

{% endblock content %}

src/the_counter/templates/the_counter/wish_list.html
{% extends "the_counter/base.html" %}

{% block content %}

    <p>Раздел: Лист желаний</p>
    <p>Записи: </p>
    <ul>
        {% for record in records %}
            <li>{{ record.date_added|date:"M d" }} : {{ record }} </li>
            <p>
                <a href="{% url 'the_counter:edit' record.id %}">Редактировать</a>
                <a href="{% url 'the_counter:delete' record.id %}">Удалить</a>
            </p>
        {% empty %}
            <li>Пока не было добавлено ни одного желания.</li>
        {% endfor %}
    </ul>

{% endblock content %}