src/accountant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from accountant import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('the_counter.urls', namespace='the_counter')),

    # Reset and Change password
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

src/the_counter/urls.py
from django.urls import path, re_path
from . import views
"""Defines URL schemes for the_counter"""

app_name = 'the_counter'
urlpatterns = [
    # Home page
    path('', views.index, name="index"),

    # Budget parts
    path('budget/', views.budget, name="budget_parts"),

    # Income_Records
    path('budget/income/', views.income_records, name="income_records"),

    # Expenses_Records
    path('budget/expenses/', views.expenses_records, name="expenses_records"),

    # WishList_Records
    path('budget/wish_list/', views.wish_list, name="wish_list"),

    # New_Record
    path('budget/new_record/', views.new_record, name="new_record"),

    # Edit_Record
    re_path(r'^edit_record/(?P<record_id>\d+)/$', views.edit_record, name="edit"),

    # Delete_Record
    re_path(r'^delete_record/(?P<record_id>\d+)/$', views.delete_record, name="delete"),
]

src/users/urls.py
from django.urls import path

from . import views

"""Defines URL schemes for users"""

app_name = 'users'
urlpatterns = [
    # Registration
    path('register/', views.registration_view, name='register'),

    # Login page
    path('login/', views.login_view, name='login'),

    # Logout
    path('logout/', views.logout_view, name='logout'),

    # User Account
    path('user/', views.account_view, name='user'),

]

src/the_counter/models.py
from django.db import models
from datetime import date


class Record(models.Model):
    """"New budget record"""
    class Item(models.TextChoices):
        INCOME = 'income', 'Текущие доходы'
        EXPENSES = 'expenses', 'Текущие расходы'
        WISHLIST = 'wish_list', 'Лист желаний'

    budget_item = models.CharField(
        max_length=9,
        choices=Item.choices,
        default=Item.INCOME,
        verbose_name='Статья бюджета'
    )

    money = models.FloatField(verbose_name='Размер')
    item_description = models.CharField(max_length=200, verbose_name='Описание')
    date_added = models.DateField(default=date.today, verbose_name='Дата')

    def __str__(self):
        """Returns the stream representation of the model"""
        return ' - '.join([str(self.money), self.item_description])

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

src/the_counter/forms.py
from django.forms import ModelForm, Textarea
from .models import Record
from django.utils.translation import gettext_lazy as _


class RecordForm(ModelForm):
    class Meta:
        model = Record
        fields = '__all__'
        # exclude = ['date_added']
        labels = {
            'item_description': _('Назначение'),
        }
        help_texts = {
            'item_description': _('Добавьте описание вашей записи'),
        }
        error_messages = {
            'item_description': {
                'max_length': _("Максимальная длинна поля должна не привышать 200 символов"),
            },
        }
        widgets = {
            'item_description': Textarea(attrs={'cols': 80, 'rows': 2}),
        }

src/the_counter/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Record
from .forms import RecordForm


def index(request):
    """Home page of The_counter apps"""
    return render(request, 'the_counter/index.html')


def budget(request):
    """Shows budget parts"""
    income = 0
    expenses = 0
    wishes = 0
    eggs = Record.objects.all()
    for spam in eggs:
        if spam.budget_item == 'income':
            income += spam.money
        elif spam.budget_item == 'expenses':
            expenses += spam.money
        elif spam.budget_item == 'wish_list':
            wishes += spam.money
    context = {'income': income, 'expenses': expenses, 'wishes': wishes}
    return render(request, 'the_counter/budget_parts.html', context)


def income_records(request):
    """List of Income records"""
    records = Record.objects.filter(budget_item='income')
    context = {'records': records}
    return render(request, 'the_counter/income_records.html', context)


def expenses_records(request):
    """List of Expenses records"""
    records = Record.objects.filter(budget_item='expenses')
    context = {'records': records}
    return render(request, 'the_counter/expenses_records.html', context)


def wish_list(request):
    """List of Wish_list records"""
    records = Record.objects.filter(budget_item='wish_list')
    context = {'records': records}
    return render(request, 'the_counter/wish_list.html', context)


def new_record(request):
    """Adding a new record"""
    if request.method != 'POST':
        # Data have not been send, creating empty form
        form = RecordForm()
    else:
        # POST data sent, process data
        form = RecordForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('budget_parts'))

    context = {'form': form}
    return render(request, 'the_counter/new_record.html', context)


def edit_record(request, record_id):
    """Edits an existing record"""
    record = Record.objects.get(id=record_id)

    if request.method != 'POST':
        # Original request; the form is filled with the data of the current record
        form = RecordForm(instance=record)
    else:
        # Sending POST data; process data
        form = RecordForm(instance=record, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('budget_parts'))

    context = {'record': record, 'form': form}
    return render(request, 'the_counter/edit_record.html', context)


def delete_record(request, record_id):
    """Delete record"""
    record = Record.objects.get(id=record_id)
    record.delete()
    return HttpResponseRedirect(reverse('budget_parts'))

src/the_counter/templates/snippets/footer.html
<!-- FOOTER -->
<hr>
<div class="d-flex flex-row align-items-center footer">
  <p class="m-auto">The Counter | 2020</p>
</div>
<!-- END FOOTER -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

src/the_counter/templates/snippets/header.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="{% static "style.css" %}">

<!-- HEADER -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">
    <a class="blog-header-logo text-dark">The Counter</a>
    {% if request.user.is_authenticated %}
    <a class="p-1 text-dark"> Привет, {{  request.user.username }}</a>
    {% endif %}
  </h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="{% url 'the_counter:index' %}">Главная</a>
    {% if request.user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url 'the_counter:budget_parts' %}">Категории</a>
      <a class="p-2 text-dark" href="{% url 'users:user' %}">Профиль</a>
      <a class="p-2 text-dark" href="{% url 'users:logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'users:login' %}">Войти</a>
      <a class="btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
    {% endif %}
  </nav>
</div>
<!-- END HEADER -->